(function () {
    /* LOADER */
    var loader = document.getElementById('loader'), loBar = document.getElementById('lo-bar'), loPct = document.getElementById('lo-pct'), loStat = document.getElementById('lo-status'), prog = 0, stepIdx = 0;
    var steps = [{ at: 12, msg: 'Loading assets' }, { at: 30, msg: 'Initializing Three.js' }, { at: 52, msg: 'Building particle field' }, { at: 70, msg: 'Rendering geometry' }, { at: 85, msg: 'Compiling shaders' }, { at: 96, msg: 'Launching portfolio' }, { at: 100, msg: 'Ready' }];
    document.body.style.overflow = 'hidden';
    function loaderTick() { var t = steps[stepIdx] ? steps[stepIdx].at : 100; prog += (t - prog) * 0.055 + 0.25; if (prog >= t) { prog = t; if (steps[stepIdx]) { loStat.textContent = steps[stepIdx].msg; stepIdx++; } } var p = Math.min(100, Math.round(prog)); loBar.style.width = p + '%'; loPct.textContent = p + '%'; if (p < 100) { requestAnimationFrame(loaderTick); } else { setTimeout(function () { loader.classList.add('hide'); document.body.style.overflow = ''; setTimeout(function () { loader.style.display = 'none'; }, 950); }, 350); } }
    requestAnimationFrame(loaderTick);

    /* HAMBURGER */
    var menuBtn = document.getElementById('menu-btn');
    var mobMenu = document.getElementById('mobile-menu');
    var menuOpen = false;
    function openMenu() { menuOpen = true; menuBtn.classList.add('open'); mobMenu.classList.add('open'); document.body.style.overflow = 'hidden'; }
    function closeMenu() { menuOpen = false; menuBtn.classList.remove('open'); mobMenu.classList.remove('open'); document.body.style.overflow = ''; }
    window.closeMenu = closeMenu;
    menuBtn.addEventListener('click', function () { menuOpen ? closeMenu() : openMenu(); });
    document.addEventListener('keydown', function (e) { if (e.key === 'Escape' && menuOpen) closeMenu(); });

    /* CURSOR */
    var cur = document.getElementById('cursor'), ring = document.getElementById('cursor-ring'), mx = 0, my = 0, rx = 0, ry = 0;
    document.addEventListener('mousemove', function (e) { mx = e.clientX; my = e.clientY; cur.style.left = mx + 'px'; cur.style.top = my + 'px'; });
    (function lr() { rx += (mx - rx) * .12; ry += (my - ry) * .12; ring.style.left = rx + 'px'; ring.style.top = ry + 'px'; requestAnimationFrame(lr); })();
    document.querySelectorAll('a,button').forEach(function (el) { el.addEventListener('mouseenter', function () { cur.style.width = '18px'; cur.style.height = '18px'; }); el.addEventListener('mouseleave', function () { cur.style.width = '10px'; cur.style.height = '10px'; }); });

    /* THREE.JS */
    var bgC = document.getElementById('bg-canvas'), scene = new THREE.Scene(), cam = new THREE.PerspectiveCamera(75, innerWidth / innerHeight, 0.1, 1000), renderer = new THREE.WebGLRenderer({ canvas: bgC, antialias: true, alpha: true });
    renderer.setSize(innerWidth, innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); cam.position.z = 30;
    var pCount = 2800, pPos = new Float32Array(pCount * 3), pCol = new Float32Array(pCount * 3);
    for (var i = 0; i < pCount * 3; i += 3) { pPos[i] = (Math.random() - .5) * 110; pPos[i + 1] = (Math.random() - .5) * 110; pPos[i + 2] = (Math.random() - .5) * 110; if (Math.random() < .6) { pCol[i] = 0; pCol[i + 1] = .96; pCol[i + 2] = .77; } else { pCol[i] = .96; pCol[i + 1] = .65; pCol[i + 2] = .14; } }
    var geoP = new THREE.BufferGeometry(); geoP.setAttribute('position', new THREE.BufferAttribute(pPos, 3)); geoP.setAttribute('color', new THREE.BufferAttribute(pCol, 3));
    var pts = new THREE.Points(geoP, new THREE.PointsMaterial({ size: .16, vertexColors: true, transparent: true, opacity: .65 })); scene.add(pts);
    function wire(g, c, x, y, z) { var m = new THREE.Mesh(g, new THREE.MeshBasicMaterial({ color: c, wireframe: true, transparent: true, opacity: .07 })); m.position.set(x, y, z); scene.add(m); return m; }
    var ico = wire(new THREE.IcosahedronGeometry(8, 1), 0x00f5c4, 18, -4, -10), tor = wire(new THREE.TorusGeometry(6, 2, 16, 40), 0xf5a623, -18, 6, -15), oct = wire(new THREE.OctahedronGeometry(5), 0x00f5c4, -5, -10, -5);
    var cmx = 0, cmy = 0, tick = 0;
    document.addEventListener('mousemove', function (e) { cmx = (e.clientX / innerWidth - .5) * 2; cmy = (e.clientY / innerHeight - .5) * 2; });
    (function anim() { requestAnimationFrame(anim); tick += .005; pts.rotation.y = tick * .05 + cmx * .03; pts.rotation.x = cmy * .02; ico.rotation.y = tick * .3; ico.rotation.x = tick * .2; tor.rotation.x = tick * .2; tor.rotation.z = tick * .15; oct.rotation.y = -tick * .25; oct.rotation.x = tick * .18; cam.position.x += (cmx * 2 - cam.position.x) * .03; cam.position.y += (-cmy * 2 - cam.position.y) * .03; renderer.render(scene, cam); })();
    window.addEventListener('resize', function () { cam.aspect = innerWidth / innerHeight; cam.updateProjectionMatrix(); renderer.setSize(innerWidth, innerHeight); });

    /* SCROLL REVEAL */
    var revIO = new IntersectionObserver(function (es) { es.forEach(function (e) { if (e.isIntersecting) e.target.classList.add('visible'); }); }, { threshold: .15 });
    document.querySelectorAll('.reveal').forEach(function (el) { revIO.observe(el); });
    var eduIO = new IntersectionObserver(function (es) { es.forEach(function (e) { if (e.isIntersecting) e.target.classList.add('visible'); }); }, { threshold: .2 });
    document.querySelectorAll('.edu-item').forEach(function (el, i) { el.style.transitionDelay = (i * .15) + 's'; eduIO.observe(el); });

    /* ABOUT TILT */
    var tc = document.getElementById('tilt-card');
    tc.addEventListener('mousemove', function (e) { var r = tc.getBoundingClientRect(); tc.style.transform = 'perspective(600px) rotateY(' + ((e.clientX - r.left - r.width / 2) / (r.width / 2) * 15) + 'deg) rotateX(' + ((e.clientY - r.top - r.height / 2) / (r.height / 2) * -15) + 'deg) scale(1.04)'; tc.style.transition = 'transform .05s'; });
    tc.addEventListener('mouseleave', function () { tc.style.transform = ''; tc.style.transition = 'transform .5s ease'; });
    var cntIO = new IntersectionObserver(function (es) { es.forEach(function (e) { if (!e.isIntersecting) return; e.target.querySelectorAll('[data-target]').forEach(function (el) { var t = +el.dataset.target, s = t / 40, v = 0; var id = setInterval(function () { v += s; if (v >= t) { v = t; clearInterval(id); } el.textContent = Math.round(v) + '+'; }, 30); }); cntIO.unobserve(e.target); }); }, { threshold: .5 });
    cntIO.observe(document.querySelector('.about-visual'));

    /* SKILLS */
    var skIO = new IntersectionObserver(function (es) { es.forEach(function (e) { if (!e.isIntersecting) return; e.target.querySelectorAll('.skill-chip:not(.sk-hidden)').forEach(function (c, i) { setTimeout(function () { c.classList.add('sk-visible'); }, i * 80); }); skIO.unobserve(e.target); }); }, { threshold: .1 });
    skIO.observe(document.getElementById('skills-grid'));
    document.querySelectorAll('.skill-tab').forEach(function (tab) { tab.addEventListener('click', function () { document.querySelectorAll('.skill-tab').forEach(function (t) { t.classList.remove('active'); }); tab.classList.add('active'); var cat = tab.dataset.cat; document.querySelectorAll('.skill-chip').forEach(function (c, i) { if (cat === 'all' || c.dataset.cat === cat) { c.classList.remove('sk-hidden', 'sk-visible'); setTimeout(function () { c.classList.add('sk-visible'); }, i * 60); } else { c.classList.add('sk-hidden'); c.classList.remove('sk-visible'); } }); }); });
    document.querySelectorAll('.skill-chip').forEach(function (chip) { var spot = chip.querySelector('.chip-spot'); var skc = getComputedStyle(chip).getPropertyValue('--sk-color').trim(); chip.addEventListener('mousemove', function (e) { var r = chip.getBoundingClientRect(); spot.style.background = 'radial-gradient(110px circle at ' + (e.clientX - r.left) + 'px ' + (e.clientY - r.top) + 'px,' + skc + '33,transparent 70%)'; }); chip.addEventListener('mouseleave', function () { spot.style.background = 'none'; }); var stx = 0, sty = 0, scx = 0, scy = 0, sraf; chip.addEventListener('mousemove', function (e) { var r = chip.getBoundingClientRect(); stx = ((e.clientY - r.top - r.height / 2) / (r.height / 2)) * -12; sty = ((e.clientX - r.left - r.width / 2) / (r.width / 2)) * 12; cancelAnimationFrame(sraf); (function sp() { scx += (stx - scx) * .14; scy += (sty - scy) * .14; chip.style.transform = 'perspective(600px) rotateX(' + scx + 'deg) rotateY(' + scy + 'deg) scale(1.05)'; if (Math.abs(stx - scx) > .05 || Math.abs(sty - scy) > .05) sraf = requestAnimationFrame(sp); })(); }); chip.addEventListener('mouseleave', function () { stx = 0; sty = 0; cancelAnimationFrame(sraf); (function sb() { scx += (0 - scx) * .14; scy += (0 - scy) * .14; chip.style.transform = 'perspective(600px) rotateX(' + scx + 'deg) rotateY(' + scy + 'deg) scale(1)'; if (Math.abs(scx) > .05 || Math.abs(scy) > .05) sraf = requestAnimationFrame(sb); else chip.style.transform = ''; })(); }); chip.addEventListener('click', function (e) { var r = chip.getBoundingClientRect(); var rip = document.createElement('div'); rip.className = 'sk-ripple'; var sz = Math.max(r.width, r.height) * .5; rip.style.cssText = 'width:' + sz + 'px;height:' + sz + 'px;left:' + (e.clientX - r.left - sz / 2) + 'px;top:' + (e.clientY - r.top - sz / 2) + 'px'; chip.appendChild(rip); setTimeout(function () { rip.remove(); }, 600); }); });

    /* PROJECT CARDS */
    var prIO = new IntersectionObserver(function (es) { es.forEach(function (e) { if (!e.isIntersecting) return; e.target.querySelectorAll('.proj-card').forEach(function (c, i) { setTimeout(function () { c.classList.add('visible'); }, i * 120); }); prIO.unobserve(e.target); }); }, { threshold: .1 });
    prIO.observe(document.querySelector('.projects-grid'));
    function h2r(h) { return { r: parseInt(h.slice(1, 3), 16), g: parseInt(h.slice(3, 5), 16), b: parseInt(h.slice(5, 7), 16) }; }
    document.querySelectorAll('.proj-card').forEach(function (card) { var rgb = h2r(getComputedStyle(card).getPropertyValue('--pc').trim()); var pcan = card.querySelector('.pc-canvas'); var pctx = pcan.getContext('2d'); var pp = [], run = false; card.addEventListener('mouseenter', function () { var vr = card.querySelector('.pc-visual').getBoundingClientRect(); pcan.width = vr.width; pcan.height = vr.height; run = true; pp = []; (function lp() { if (!run) return; pctx.clearRect(0, 0, pcan.width, pcan.height); if (Math.random() < .4) for (var i = 0; i < 5; i++)pp.push({ x: Math.random() * pcan.width, y: pcan.height * .4, vx: (Math.random() - .5) * 2.2, vy: -Math.random() * 1.8 - .4, life: 1, size: Math.random() * 2.5 + 1 }); pp = pp.filter(function (p) { return p.life > 0.01; }); pp.forEach(function (p) { p.x += p.vx; p.y += p.vy; p.vy += .025; p.life -= .022; pctx.beginPath(); pctx.arc(p.x, p.y, Math.max(0, p.size), 0, Math.PI * 2); pctx.fillStyle = 'rgba(' + rgb.r + ',' + rgb.g + ',' + rgb.b + ',' + (p.life * .55) + ')'; pctx.fill(); }); requestAnimationFrame(lp); })(); }); card.addEventListener('mouseleave', function () { run = false; pctx.clearRect(0, 0, pcan.width, pcan.height); }); var spot = card.querySelector('.pc-spot'); card.addEventListener('mousemove', function (e) { var rc = card.getBoundingClientRect(); spot.style.background = 'radial-gradient(240px circle at ' + (e.clientX - rc.left) + 'px ' + (e.clientY - rc.top) + 'px,rgba(' + rgb.r + ',' + rgb.g + ',' + rgb.b + ',.09),transparent 70%)'; }); card.addEventListener('mouseleave', function () { spot.style.background = 'none'; }); var ptx = 0, pty = 0, pcx = 0, pcy = 0, praf; card.addEventListener('mousemove', function (e) { var rc = card.getBoundingClientRect(); ptx = ((e.clientY - rc.top - rc.height / 2) / (rc.height / 2)) * -8; pty = ((e.clientX - rc.left - rc.width / 2) / (rc.width / 2)) * 8; cancelAnimationFrame(praf); (function sp() { pcx += (ptx - pcx) * .12; pcy += (pty - pcy) * .12; card.style.transform = 'perspective(900px) rotateX(' + pcx + 'deg) rotateY(' + pcy + 'deg) translateY(-5px)'; if (Math.abs(ptx - pcx) > .05 || Math.abs(pty - pcy) > .05) praf = requestAnimationFrame(sp); })(); }); card.addEventListener('mouseleave', function () { ptx = 0; pty = 0; cancelAnimationFrame(praf); (function sb() { pcx += (0 - pcx) * .12; pcy += (0 - pcy) * .12; card.style.transform = 'perspective(900px) rotateX(' + pcx + 'deg) rotateY(' + pcy + 'deg)'; if (Math.abs(pcx) > .05 || Math.abs(pcy) > .05) praf = requestAnimationFrame(sb); else card.style.transform = ''; })(); }); });

    /* SCROLL CHARACTER */
    var cc = document.getElementById('char-canvas'), cctx = cc.getContext('2d'), tc2 = document.getElementById('char-trail'), tctx = tc2.getContext('2d');
    cctx.imageSmoothingEnabled = false;
    function resizeTrail() { tc2.width = innerWidth; tc2.height = innerHeight; } resizeTrail();
    window.addEventListener('resize', resizeTrail);
    var SC = 8, N = null, W = '#e8e8f0', C = '#00f5c4', D = '#0c0c14', G = '#5a5a72', Y = '#f5a623', B = '#1a1a2e', P = '#b464ff', R = '#ff6b6b';
    var frames = [[[N, N, N, W, W, N, N, N], [N, N, W, W, W, W, N, N], [N, W, C, C, C, C, W, N], [N, W, C, D, D, C, W, N], [N, W, C, D, D, C, W, N], [N, W, C, C, C, C, W, N], [N, N, W, W, W, W, N, N], [N, W, W, G, G, W, W, N], [Y, W, W, W, W, W, W, Y], [Y, W, R, W, W, P, W, Y], [N, W, W, G, G, W, W, N], [N, W, G, W, W, G, W, N], [N, W, G, W, W, G, W, N], [N, B, B, N, N, B, B, N], [N, B, N, N, N, N, B, N], [N, N, N, N, N, N, N, N]], [[N, N, N, W, W, N, N, N], [N, N, W, W, W, W, N, N], [N, W, C, C, C, C, W, N], [N, W, C, D, D, C, W, N], [N, W, C, D, D, C, W, N], [N, W, C, C, C, C, W, N], [N, N, W, W, W, W, N, N], [W, W, W, G, G, W, W, N], [Y, W, W, W, W, W, W, Y], [Y, W, R, W, W, P, W, Y], [N, W, W, G, G, W, W, N], [N, N, W, G, W, G, W, N], [N, N, W, W, N, W, G, N], [N, N, B, B, N, N, B, N], [N, N, B, N, N, N, N, N], [N, N, N, N, N, N, N, N]], [[N, N, N, W, W, N, N, N], [N, N, W, W, W, W, N, N], [N, W, C, C, C, C, W, N], [N, W, C, D, D, C, W, N], [N, W, C, D, D, C, W, N], [N, W, C, C, C, C, W, N], [N, N, W, W, W, W, N, N], [N, W, W, G, G, W, W, W], [Y, W, W, W, W, W, W, Y], [Y, W, R, W, W, P, W, Y], [N, W, W, G, G, W, W, N], [N, W, G, W, W, G, N, N], [N, W, G, N, W, W, N, N], [N, N, B, N, B, B, N, N], [N, N, N, N, B, N, N, N], [N, N, N, N, N, N, N, N]], [[N, N, N, W, W, N, N, N], [N, N, W, W, W, W, N, N], [N, W, C, C, C, C, W, N], [N, W, C, D, D, C, W, N], [N, W, C, D, D, C, W, N], [N, W, C, C, C, C, W, N], [N, N, W, W, W, W, N, N], [W, W, W, G, G, W, W, N], [Y, W, W, W, W, W, W, Y], [Y, W, R, W, W, P, W, Y], [N, W, W, G, G, W, W, N], [N, W, G, W, W, G, N, N], [N, W, G, W, N, W, N, N], [N, N, B, N, N, B, N, N], [N, N, N, N, N, B, N, N], [N, N, N, N, N, N, N, N]]];
    function drawFrame(fi, flip) { cctx.clearRect(0, 0, cc.width, cc.height); var fr = frames[fi], cols = 8, rows = 16, ox = (cc.width - cols * SC) / 2, oy = (cc.height - rows * SC) / 2; for (var r = 0; r < rows; r++)for (var col = 0; col < cols; col++) { var color = fr[r][flip ? (cols - 1 - col) : col]; if (!color) continue; cctx.fillStyle = color; cctx.fillRect(ox + col * SC, oy + r * SC, SC, SC); } }
    var lastSc = 0, scSpeed = 0, fIdx = 0, fTick = 0, facing = false, charY = 80, tgtY = 80, moving = false, idleT = null, iBob = 0, trail = [];
    function getTgtY() { var ms = document.body.scrollHeight - innerHeight; return 60 + (ms > 0 ? scrollY / ms : 0) * (innerHeight - 160); }
    window.addEventListener('scroll', function () { var d = scrollY - lastSc; scSpeed = d; lastSc = scrollY; moving = true; facing = d > 0; clearTimeout(idleT); idleT = setTimeout(function () { moving = false; }, 180); }, { passive: true });
    function spawnT() { var rc = cc.getBoundingClientRect(); trail.push({ x: rc.left + cc.width / 2 + (Math.random() - .5) * 16, y: rc.top + cc.height * .72, vx: (Math.random() - .5) * 1.8, vy: -Math.random() * 1.2 - .4, life: 1, size: Math.random() * 3 + 1, color: Math.random() < .6 ? '#00f5c4' : '#f5a623' }); }
    (function loop() { requestAnimationFrame(loop); tgtY = getTgtY(); charY += (tgtY - charY) * .08; if (moving) { fTick += Math.abs(scSpeed) * .14 + .1; if (fTick >= 1) { fTick = 0; fIdx = (fIdx + 1) % 4; } cc.style.top = charY + 'px'; cc.style.filter = 'drop-shadow(0 0 12px #00f5c4)'; if (Math.random() < .3) spawnT(); } else { fIdx = 0; iBob += .05; cc.style.top = (charY + Math.sin(iBob) * 3) + 'px'; cc.style.filter = 'drop-shadow(0 0 7px #00f5c4)'; } drawFrame(fIdx, facing); tctx.clearRect(0, 0, tc2.width, tc2.height); trail = trail.filter(function (p) { return p.life > 0.01; }); trail.forEach(function (p) { p.x += p.vx; p.y += p.vy; p.vy += .04; p.life -= .04; tctx.beginPath(); tctx.arc(p.x, p.y, Math.max(0, p.size * p.life), 0, Math.PI * 2); tctx.fillStyle = p.color + Math.floor(p.life * 200).toString(16).padStart(2, '0'); tctx.fill(); }); })();
    cc.addEventListener('click', function () { var secs = document.querySelectorAll('section'); secs[Math.floor(Math.random() * secs.length)].scrollIntoView({ behavior: 'smooth' }); });
    drawFrame(0, false);
})();